// Natural Experiment Finder, curated database of canonical
// identification strategies in economics (Card-Krueger 1994, Mariel boatlift,
// Vietnam draft lottery, Oregon Medicaid, etc.). Searchable by question type,
// method, treatment, and AP-CED concept tag.

export type IdMethod =
  | "DiD"             // difference-in-differences
  | "RDD"             // regression discontinuity
  | "IV"              // instrumental variables
  | "RCT"             // randomized controlled trial
  | "Synthetic"       // synthetic control
  | "EventStudy"      // event-study / staggered DiD
  | "Bunching"        // bunching / kink design
  | "Shift-Share"     // Bartik / shift-share IV
  | "Lottery";        // natural lottery / quasi-RCT

export interface NaturalExperiment {
  id: string;
  title: string;
  method: IdMethod;
  authors: string;
  year: number;
  journal: string;
  doi?: string;
  field: ("Labor" | "Macro" | "Health" | "Education" | "Trade" | "Finance" | "Public" | "Crime" | "Development")[];
  question: string;          // research question
  treatment: string;         // what was the "shock"
  finding: string;           // key magnitude
  identification: string;    // why it identifies the causal effect
  diagnostics: string[];     // what makes/breaks the design
  apTag?: string[];          // AP-Macro/Micro CED concept tags
  keywords: string[];
}

export const NATURAL_EXPERIMENTS: NaturalExperiment[] = [
  {
    id: "card-krueger-1994",
    title: "Minimum Wage and Employment: NJ–PA Fast Food",
    method: "DiD",
    authors: "Card & Krueger",
    year: 1994,
    journal: "American Economic Review",
    doi: "10.1257/aer.84.4.772",
    field: ["Labor", "Public"],
    question: "Does raising the minimum wage reduce employment?",
    treatment: "NJ raised the minimum wage from $4.25 to $5.05 in April 1992; PA did not.",
    finding: "No statistically significant employment loss; small positive employment effect of +2.76 FTE per store.",
    identification: "Pre/post comparison of NJ (treated) vs PA (control) eateries 8 months apart, differencing out chain-level fixed effects.",
    diagnostics: ["Parallel pre-trends", "No anticipation effect", "SUTVA: workers don't migrate across border"],
    apTag: ["Labor markets", "Price floors", "Welfare analysis"],
    keywords: ["minimum wage", "employment", "monopsony"],
  },
  {
    id: "card-mariel-1990",
    title: "Mariel Boatlift and Miami Wages",
    method: "Synthetic",
    authors: "Card",
    year: 1990,
    journal: "ILR Review",
    doi: "10.1177/001979399004300205",
    field: ["Labor", "Development"],
    question: "Do labor supply shocks lower native wages?",
    treatment: "125,000 Cuban refugees arrived in Miami in 1980, expanding the labor force ~7% overnight.",
    finding: "No measurable wage decline for Miami's low-skill native workers vs synthetic control of similar US cities.",
    identification: "Synthetic-control: weighted combination of Atlanta/Houston/LA/Tampa replicates pre-1980 Miami wage path.",
    diagnostics: ["Borjas (2017) re-analysis disputes magnitude", "Sample composition sensitivity", "Donor-pool selection"],
    apTag: ["Labor supply", "Immigration", "Equilibrium wage"],
    keywords: ["immigration", "labor supply", "synthetic control"],
  },
  {
    id: "angrist-vietnam-1990",
    title: "Vietnam Draft Lottery and Lifetime Earnings",
    method: "IV",
    authors: "Angrist",
    year: 1990,
    journal: "American Economic Review",
    doi: "10.1257/aer.80.3.313",
    field: ["Labor", "Education"],
    question: "What is the causal effect of military service on civilian earnings?",
    treatment: "1970–1972 lotteries randomly assigned draft eligibility by birthday.",
    finding: "Vietnam veterans earned 15% less than non-veterans in the early 1980s; effect dissipated by 2000.",
    identification: "Lottery number is randomly assigned ⇒ valid instrument for veteran status; LATE estimator.",
    diagnostics: ["First-stage F=23 (strong)", "Exclusion: lottery affects earnings only via service", "Monotonicity holds"],
    apTag: ["Human capital", "Returns to education", "LATE"],
    keywords: ["draft", "military", "instrumental variable", "earnings"],
  },
  {
    id: "oregon-medicaid-2008",
    title: "Oregon Health Insurance Experiment",
    method: "Lottery",
    authors: "Finkelstein, Taubman, Wright, Bernstein, Gruber, Newhouse, et al.",
    year: 2012,
    journal: "Quarterly Journal of Economics",
    doi: "10.1093/qje/qjs020",
    field: ["Health", "Public"],
    question: "What is the causal effect of Medicaid coverage on health and finances?",
    treatment: "Oregon held a lottery in 2008 to allocate ~10,000 limited Medicaid slots among 90,000 applicants.",
    finding: "Coverage ↑ utilization 25%, ↓ catastrophic medical expenditure 81%, no detectable improvement in objective biomarkers (HbA1c, BP) at 2 years.",
    identification: "Lottery winners vs losers among adults who all wanted insurance ⇒ true RCT for an intent-to-treat design.",
    diagnostics: ["Compliance rate ~30% (winning lottery doesn't auto-enroll)", "Power for biomarkers"],
    apTag: ["Public goods", "Insurance", "Cost-benefit"],
    keywords: ["Medicaid", "health insurance", "lottery", "RCT"],
  },
  {
    id: "lee-bds-2008",
    title: "Incumbency Advantage in US House",
    method: "RDD",
    authors: "Lee",
    year: 2008,
    journal: "Journal of Econometrics",
    doi: "10.1016/j.jeconom.2007.05.004",
    field: ["Public"],
    question: "Does winning election cause future electoral advantage (versus selection)?",
    treatment: "Barely-winning vs barely-losing US House candidates.",
    finding: "Winning by 0.1% raises next-cycle vote share by 7–8pp on average.",
    identification: "Sharp RDD at 50% vote-share threshold; treatment is as good as random in narrow bandwidth.",
    diagnostics: ["McCrary density test", "Covariate balance at threshold", "Bandwidth sensitivity (IK, CCT)"],
    apTag: ["Public choice", "Political economy"],
    keywords: ["RDD", "elections", "incumbency"],
  },
  {
    id: "ada-acs-2010",
    title: "Manufacturing China Shock",
    method: "Shift-Share",
    authors: "Autor, Dorn, Hanson",
    year: 2013,
    journal: "American Economic Review",
    doi: "10.1257/aer.103.6.2121",
    field: ["Trade", "Labor"],
    question: "Did Chinese import competition reduce US manufacturing employment?",
    treatment: "Surge in US imports from China after WTO accession, 1991–2007.",
    finding: "Local labor markets with greater exposure lost ~2.4M manufacturing jobs and saw persistent wage declines.",
    identification: "Bartik IV: industry-employment shares × China-export growth in non-US economies; SOO LM diagnostics in Borusyak-Hull-Jaravel (2022).",
    diagnostics: ["Goldsmith-Pinkham-Sorkin pre-period exposure test", "Adão-Kolesar-Morales SE adjustment"],
    apTag: ["International trade", "Comparative advantage"],
    keywords: ["trade shock", "Bartik", "manufacturing"],
  },
  {
    id: "abadie-basque-2003",
    title: "Economic Cost of Conflict: Basque Country",
    method: "Synthetic",
    authors: "Abadie & Gardeazabal",
    year: 2003,
    journal: "American Economic Review",
    doi: "10.1257/000282803321455188",
    field: ["Macro", "Public"],
    question: "How does terrorism affect regional economic output?",
    treatment: "ETA terrorist activity in the Basque Country starting late 1960s.",
    finding: "Per-capita GDP fell ~10% relative to a synthetic Basque-without-terrorism.",
    identification: "Convex combination of other Spanish regions reproduces pre-conflict GDP path; post-conflict gap = treatment effect.",
    diagnostics: ["Donor pool", "Pre-period MSPE", "Permutation inference"],
    apTag: ["Growth", "Macro shocks"],
    keywords: ["terrorism", "synthetic control", "regional GDP"],
  },
  {
    id: "duflo-school-2001",
    title: "Indonesian School Construction (INPRES)",
    method: "DiD",
    authors: "Duflo",
    year: 2001,
    journal: "American Economic Review",
    doi: "10.1257/aer.91.4.795",
    field: ["Education", "Development"],
    question: "What is the return to a year of schooling?",
    treatment: "Indonesia built 61,000 primary schools 1973–1978; intensity varied by district.",
    finding: "Each additional school per 1,000 children → 0.12 extra years of education and 1.5–2.7% higher wages.",
    identification: "DiD by birth-cohort (treated: ages 2–6 in 1974) × district program intensity.",
    diagnostics: ["Parallel trends in pre-program cohorts", "Migration as confounder"],
    apTag: ["Human capital", "Returns to education"],
    keywords: ["education returns", "schooling", "Indonesia"],
  },
  {
    id: "miguel-deworming-2004",
    title: "Worms: Health and Education in Kenya",
    method: "RCT",
    authors: "Miguel & Kremer",
    year: 2004,
    journal: "Econometrica",
    doi: "10.1111/j.1468-0262.2004.00481.x",
    field: ["Health", "Education", "Development"],
    question: "Do school-based deworming programs improve attendance?",
    treatment: "75 Kenyan primary schools randomly phased into deworming 1998–2001.",
    finding: "Treated schools: ~25% drop in absenteeism; positive cross-school spillovers via lower transmission.",
    identification: "Cluster RCT at school level, randomized into 3 phase-in waves.",
    diagnostics: ["Spillover correction (SUTVA violation)", "Aiken et al. 2015 reanalysis"],
    apTag: ["Public health", "Externalities"],
    keywords: ["deworming", "RCT", "education"],
  },
  {
    id: "saez-bunching-2010",
    title: "Bunching at Tax Kinks",
    method: "Bunching",
    authors: "Saez",
    year: 2010,
    journal: "AEJ Economic Policy",
    doi: "10.1257/pol.2.3.180",
    field: ["Public", "Labor"],
    question: "How elastic is taxable income with respect to marginal rates?",
    treatment: "Kinks in the US federal tax schedule (e.g., EITC plateau, bracket boundaries).",
    finding: "Self-employed bunch sharply at EITC kink ⇒ ETI ≈ 0.25; wage earners barely respond.",
    identification: "Excess mass at the kink relative to a smooth counterfactual density identifies the elasticity.",
    diagnostics: ["Counterfactual polynomial choice", "Optimization frictions", "Round-number heaping"],
    apTag: ["Taxation", "Elasticity", "Optimal tax"],
    keywords: ["bunching", "ETI", "EITC", "taxes"],
  },
  {
    id: "card-2003-card-card",
    title: "Quarterly Earnings Announcements as Event Study",
    method: "EventStudy",
    authors: "Fama-French / Ball-Brown lineage",
    year: 1968,
    journal: "Journal of Accounting Research",
    field: ["Finance"],
    question: "Are stock prices efficient relative to public information?",
    treatment: "Quarterly earnings announcements at scheduled dates.",
    finding: "Cumulative abnormal returns spike on announcement day; post-announcement drift ~3% over 60 trading days (anomaly).",
    identification: "Market-model expected return removed; CAR around event window isolates news effect.",
    diagnostics: ["Confounding events", "Choice of estimation window", "PEAD / drift literature"],
    apTag: ["Efficient markets", "Asset pricing"],
    keywords: ["event study", "PEAD", "earnings"],
  },
  {
    id: "romer-romer-2010",
    title: "Macroeconomic Effects of Tax Changes",
    method: "EventStudy",
    authors: "Romer & Romer",
    year: 2010,
    journal: "American Economic Review",
    doi: "10.1257/aer.100.3.763",
    field: ["Macro", "Public"],
    question: "What is the multiplier on exogenous tax changes?",
    treatment: "Narrative classification of US tax changes 1947–2007 into 'exogenous' and 'endogenous'.",
    finding: "An exogenous 1% of GDP tax cut raises GDP by ~3% within 3 years.",
    identification: "Narrative IV, Congressional Records used to classify tax changes by motivation; only exogenous (deficit-driven, ideological) used.",
    diagnostics: ["Mertens-Ravn 2013 adjustment", "Coding subjectivity", "Anticipation effects"],
    apTag: ["Fiscal multiplier", "Tax policy"],
    keywords: ["narrative IV", "fiscal", "tax multiplier"],
  },
  {
    id: "gertler-karadi-2015",
    title: "Monetary Policy Surprises and Macro Effects",
    method: "IV",
    authors: "Gertler & Karadi",
    year: 2015,
    journal: "AEJ Macroeconomics",
    doi: "10.1257/mac.20130329",
    field: ["Macro", "Finance"],
    question: "How do monetary surprises propagate to credit and output?",
    treatment: "30-min federal funds futures changes around FOMC announcements.",
    finding: "100bp tightening surprise ⇒ −1.0% IP, +20bp credit spread within 24 months.",
    identification: "High-frequency surprises are externally valid IV for the policy rate.",
    diagnostics: ["Information effect (Nakamura-Steinsson 2018)", "Tightness of identification window"],
    apTag: ["Monetary transmission", "Credit channel"],
    keywords: ["HFI", "monetary", "FOMC"],
  },
  {
    id: "deaton-rdd-2007",
    title: "Air Pollution and Mortality Around 1956 UK Clean Air Act",
    method: "DiD",
    authors: "Chay & Greenstone (genre)",
    year: 2003,
    journal: "QJE",
    doi: "10.1162/00335530360535221",
    field: ["Health", "Public"],
    question: "Do environmental regulations save lives?",
    treatment: "Clean Air Act non-attainment designations forced abatement in selected counties.",
    finding: "Counties switching to attainment status: ~5% reduction in infant mortality.",
    identification: "DiD by attainment status × year; restricted-county sample to address selection.",
    diagnostics: ["Selection on regulation", "Sorting", "Migration"],
    apTag: ["Externalities", "Pigouvian"],
    keywords: ["pollution", "mortality", "Clean Air Act"],
  },
  {
    id: "almond-sutter-2009",
    title: "1918 Influenza Pandemic and Long-Run Outcomes",
    method: "DiD",
    authors: "Almond",
    year: 2006,
    journal: "Journal of Political Economy",
    doi: "10.1086/507154",
    field: ["Health", "Labor"],
    question: "Do in-utero shocks affect adult outcomes (Barker hypothesis)?",
    treatment: "1918 flu pandemic exposure in utero, varying across birth cohorts.",
    finding: "Cohorts in utero during pandemic had 15% lower wages and 15pp higher disability rates by 1980.",
    identification: "Sharp cohort discontinuity at 1918 birth dates; comparison to surrounding cohorts.",
    diagnostics: ["Selection (mortality of pregnant mothers)", "Trend confounders"],
    apTag: ["Human capital", "Long-run"],
    keywords: ["fetal origins", "pandemic", "long-run"],
  },
  {
    id: "ackerberg-petrin-2024",
    title: "Mexico's Conditional Cash Transfer (PROGRESA)",
    method: "RCT",
    authors: "Schultz",
    year: 2004,
    journal: "Journal of Development Economics",
    field: ["Education", "Development"],
    question: "Do conditional cash transfers raise school enrollment?",
    treatment: "1997 PROGRESA randomly phased in across 506 villages; transfers tied to school attendance.",
    finding: "Secondary enrollment ↑ ~6pp for boys, ~10pp for girls in treated villages.",
    identification: "Cluster RCT at the village level over a 2-year phase-in period.",
    diagnostics: ["Compliance", "Spillovers", "General-equilibrium wage effects"],
    apTag: ["Education", "CCT", "Public policy"],
    keywords: ["CCT", "PROGRESA", "education"],
  },
  {
    id: "draca-london-2011",
    title: "London 2005 Bombings and Police Deployment",
    method: "DiD",
    authors: "Draca, Machin, Witt",
    year: 2011,
    journal: "American Economic Review",
    doi: "10.1257/aer.101.5.2157",
    field: ["Crime", "Public"],
    question: "Does police presence cause lower crime?",
    treatment: "Surge in central London police deployment after July 2005 bombings.",
    finding: "10% more police-hours → 3–4% reduction in crime in covered districts.",
    identification: "DiD across central vs non-central wards × pre/post bombing.",
    diagnostics: ["Mean reversion", "Spillover into uncovered wards"],
    apTag: ["Public safety", "Externalities"],
    keywords: ["police", "crime", "DiD"],
  },
  {
    id: "kearney-rosen-2024",
    title: "Same-Sex Marriage Legalization (Obergefell)",
    method: "EventStudy",
    authors: "Various",
    year: 2015,
    journal: "Multiple",
    field: ["Public"],
    question: "Does marriage-equality legalization affect labor and family outcomes?",
    treatment: "Obergefell v. Hodges (2015) federally legalized same-sex marriage.",
    finding: "Mental-health utilization among LGB youth fell 14% in immediate aftermath; long-run wage and household-formation effects pending.",
    identification: "Staggered DiD by state, with 2015 as universal-treatment date for late adopters.",
    diagnostics: ["Heterogeneous treatment effects (Goodman-Bacon decomposition)", "Pre-trends"],
    apTag: ["Public choice", "Household formation"],
    keywords: ["marriage", "policy", "DiD"],
  },
  {
    id: "chetty-moving-2018",
    title: "Moving to Opportunity (MTO), Long-Run",
    method: "RCT",
    authors: "Chetty, Hendren, Katz",
    year: 2016,
    journal: "American Economic Review",
    doi: "10.1257/aer.20150572",
    field: ["Public", "Labor", "Education"],
    question: "Does childhood neighborhood exposure causally improve adult outcomes?",
    treatment: "1994–98 HUD MTO experiment randomly assigned families housing vouchers conditional on moving to lower-poverty tracts.",
    finding: "Children moved before age 13: adult earnings +31%, college attendance +27%.",
    identification: "Lottery-based RCT, with reduced-form ITT and IV estimates by age at move.",
    diagnostics: ["LATE applies only to compliers", "Non-experimental quasi-replication via place effects"],
    apTag: ["Human capital", "Place effects"],
    keywords: ["MTO", "neighborhoods", "RCT"],
  },
  {
    id: "card-2018-rdd-edu",
    title: "Mortgage-Disclosure Discontinuity",
    method: "RDD",
    authors: "Bhutta, Dokko, Shan",
    year: 2017,
    journal: "Journal of Finance",
    field: ["Finance"],
    question: "Do borrower default rates change discontinuously at LTV/credit thresholds?",
    treatment: "Sharp credit-score thresholds (e.g., 620 FICO) used in mortgage underwriting.",
    finding: "Marginal borrowers just above 620 default at 1.6× the rate of those just below, adverse selection by lenders.",
    identification: "Sharp RDD at FICO=620; tight bandwidth, McCrary density continuous.",
    diagnostics: ["Manipulation around threshold", "Bandwidth choice"],
    apTag: ["Credit markets", "Asymmetric information"],
    keywords: ["FICO", "credit", "RDD"],
  },
];

export const ID_METHOD_INFO: Record<IdMethod, { name: string; gist: string; assumptions: string[] }> = {
  DiD: {
    name: "Difference-in-Differences",
    gist: "Compare change in outcomes pre vs post treatment between treated and control groups.",
    assumptions: ["Parallel trends", "No anticipation", "Stable composition (SUTVA)"],
  },
  RDD: {
    name: "Regression Discontinuity",
    gist: "Treatment is assigned by a sharp threshold on a continuous running variable.",
    assumptions: ["Continuity at cutoff", "No precise manipulation", "Smooth covariates"],
  },
  IV: {
    name: "Instrumental Variables",
    gist: "Use an exogenous shifter (instrument) of treatment that affects outcomes only via that channel.",
    assumptions: ["Relevance (strong first stage)", "Exclusion restriction", "Monotonicity (for LATE)"],
  },
  RCT: {
    name: "Randomized Controlled Trial",
    gist: "Random assignment of subjects to treatment/control eliminates selection bias.",
    assumptions: ["Successful randomization", "No spillovers", "ITT vs LATE clarity"],
  },
  Synthetic: {
    name: "Synthetic Control",
    gist: "Build a counterfactual unit as a convex combination of donor units.",
    assumptions: ["Pre-period fit", "No interference across donors", "No idiosyncratic post-shocks"],
  },
  EventStudy: {
    name: "Event Study / Staggered DiD",
    gist: "Track outcome dynamics around a discrete event date relative to expected baseline.",
    assumptions: ["Event-window cleanliness", "No confounding events", "Estimation-window stability"],
  },
  Bunching: {
    name: "Bunching / Kink",
    gist: "Use excess mass at a kink in a budget constraint to identify a behavioral elasticity.",
    assumptions: ["Counterfactual density specification", "Optimization frictions modeled", "No round-number heaping bias"],
  },
  "Shift-Share": {
    name: "Shift-Share / Bartik",
    gist: "Combine local industry shares with national industry shocks as an instrument for local exposure.",
    assumptions: ["Quasi-random pre-period shares (GPS 2020)", "No omitted shock channel", "Adão-Kolesar-Morales SE adjustment"],
  },
  Lottery: {
    name: "Natural Lottery",
    gist: "Treatment allocated by a literal lottery (Vietnam draft, Oregon Medicaid, MTO vouchers).",
    assumptions: ["Random number generator was actually random", "Non-compliers handled (LATE vs ITT)"],
  },
};
