import { forwardRef } from "react";
import { todayLong } from "@/lib/export-brief";

// A single-page printable Policy Brief. Always renders in a fixed off-screen
// container at letter-portrait dimensions so the PDF capture is consistent
// regardless of viewport or theme. Light theme baked in (dark mode is
// rendered against #fff via html2canvas backgroundColor).
//
// All copy is derived from props so the same component is reused across
// EconLever, TariffLab, Shadow Fed, Shock Simulator, and any other tool
// that wants to generate a brief.

export interface BriefRow {
  label: string;
  setting: string;
  baseline?: string;
}

export interface BriefKPI {
  label: string;
  value: string;
  tone?: "good" | "bad" | "neutral";
  delta?: string;
}

export interface PolicyBriefProps {
  toolName: string; // e.g. "EconLever"
  regimeBadge?: string; // e.g. "REGIME · MIXED / CENTRIST"
  subtitle: string; // e.g. "10-Year Projection · 2026–2036"
  configRows: BriefRow[];
  kpis: BriefKPI[];
  analysisHeadline: string;
  analysisBody: string;
  /** Optional charts area — pass any JSX (rendered at fixed width). */
  chartsNode?: React.ReactNode;
  /** Override the default disclaimer footer if needed. */
  disclaimer?: string;
}

const DEFAULT_DISCLAIMER =
  "Generated by The Mother of Econ. Illustrative simulation; coefficients calibrated to mainstream macroeconomic literature; not a substitute for DSGE/VAR analysis. See methodology page for full citations.";

export const PolicyBrief = forwardRef<HTMLDivElement, PolicyBriefProps>(
  function PolicyBrief(
    {
      toolName,
      regimeBadge,
      subtitle,
      configRows,
      kpis,
      analysisHeadline,
      analysisBody,
      chartsNode,
      disclaimer = DEFAULT_DISCLAIMER,
    },
    ref
  ) {
    return (
      <div
        ref={ref}
        // Fixed letter portrait size at ~96dpi for crisp html2canvas capture.
        style={{
          width: 816,
          padding: 48,
          background: "#ffffff",
          color: "#0f1f3d",
          fontFamily:
            "'Inter Tight', system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
          fontSize: 12,
          lineHeight: 1.5,
        }}
      >
        {/* HEADER */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            paddingBottom: 16,
            borderBottom: "1px solid #d6d3cf",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
            <div
              style={{
                width: 36,
                height: 36,
                borderRadius: 10,
                background: "#0f1f3d",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "#fff",
                fontFamily: "'Fraunces', Georgia, serif",
                fontWeight: 700,
                fontStyle: "italic",
                fontSize: 22,
                lineHeight: 1,
              }}
            >
              M
            </div>
            <div>
              <div
                style={{
                  fontFamily: "'Fraunces', Georgia, serif",
                  fontSize: 22,
                  fontWeight: 600,
                  letterSpacing: "-0.01em",
                  color: "#0f1f3d",
                }}
              >
                {toolName} <span style={{ color: "#7a3242" }}>·</span> Policy Brief
              </div>
              <div
                style={{
                  fontSize: 11,
                  color: "#6b6864",
                  marginTop: 2,
                  letterSpacing: "0.02em",
                }}
              >
                {todayLong()} · {subtitle}
              </div>
            </div>
          </div>
          {regimeBadge && (
            <div
              style={{
                background: "#0f1f3d",
                color: "#fff",
                fontSize: 9.5,
                fontWeight: 700,
                letterSpacing: "0.18em",
                textTransform: "uppercase",
                padding: "6px 12px",
                borderRadius: 999,
              }}
            >
              {regimeBadge}
            </div>
          )}
        </div>

        {/* CONFIG */}
        <SectionLabel>Policy Configuration</SectionLabel>
        <table style={{ width: "100%", borderCollapse: "collapse", marginTop: 8 }}>
          <thead>
            <tr style={{ background: "#f5f1ec" }}>
              <Th>Lever</Th>
              <Th>Setting</Th>
              <Th>U.S. Baseline (2025)</Th>
            </tr>
          </thead>
          <tbody>
            {configRows.map((r, i) => (
              <tr
                key={i}
                style={{ borderBottom: "1px solid #ebe7e1" }}
              >
                <Td style={{ fontWeight: 500 }}>{r.label}</Td>
                <Td style={{ fontWeight: 600 }}>{r.setting}</Td>
                <Td style={{ color: "#6b6864" }}>{r.baseline ?? "—"}</Td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* KPIs */}
        <SectionLabel>Projected Outcomes (10-Year Average)</SectionLabel>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: `repeat(${kpis.length}, 1fr)`,
            gap: 12,
            marginTop: 8,
          }}
        >
          {kpis.map((k, i) => (
            <div
              key={i}
              style={{
                border: "1px solid #ebe7e1",
                borderRadius: 8,
                padding: 14,
                background: "#fafaf7",
              }}
            >
              <div
                style={{
                  fontSize: 9.5,
                  letterSpacing: "0.18em",
                  textTransform: "uppercase",
                  color: "#6b6864",
                }}
              >
                {k.label}
              </div>
              <div
                style={{
                  fontFamily: "'Fraunces', Georgia, serif",
                  fontSize: 28,
                  fontWeight: 600,
                  marginTop: 4,
                  color: toneColor(k.tone),
                }}
              >
                {k.value}
              </div>
              {k.delta && (
                <div style={{ fontSize: 10.5, color: "#6b6864", marginTop: 2 }}>
                  {k.delta}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* CHARTS */}
        {chartsNode && (
          <>
            <SectionLabel>Trajectory</SectionLabel>
            <div
              style={{
                marginTop: 8,
                border: "1px solid #ebe7e1",
                borderRadius: 8,
                padding: 12,
                background: "#fafaf7",
              }}
            >
              {chartsNode}
            </div>
          </>
        )}

        {/* ANALYSIS */}
        <SectionLabel>Policy Analysis</SectionLabel>
        <div
          style={{
            fontFamily: "'Fraunces', Georgia, serif",
            fontWeight: 600,
            fontSize: 16,
            marginTop: 6,
            color: "#0f1f3d",
          }}
        >
          {analysisHeadline}
        </div>
        <p style={{ marginTop: 8, color: "#2c2a26", fontSize: 12 }}>
          {analysisBody}
        </p>

        {/* FOOTER */}
        <div
          style={{
            marginTop: 28,
            paddingTop: 14,
            borderTop: "1px solid #d6d3cf",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-start",
            gap: 24,
            fontSize: 9.5,
            color: "#6b6864",
          }}
        >
          <div style={{ flex: 1, lineHeight: 1.5 }}>{disclaimer}</div>
          <div style={{ textAlign: "right", whiteSpace: "nowrap", fontWeight: 600 }}>
            Saras Totey · econ.mom
          </div>
        </div>
      </div>
    );
  }
);

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        marginTop: 22,
        fontSize: 9.5,
        letterSpacing: "0.22em",
        textTransform: "uppercase",
        color: "#7a3242",
        fontWeight: 700,
      }}
    >
      {children}
    </div>
  );
}

function Th({ children }: { children: React.ReactNode }) {
  return (
    <th
      style={{
        textAlign: "left",
        padding: "8px 10px",
        fontSize: 9.5,
        letterSpacing: "0.18em",
        textTransform: "uppercase",
        color: "#0f1f3d",
        borderBottom: "1px solid #d6d3cf",
        fontWeight: 700,
      }}
    >
      {children}
    </th>
  );
}

function Td({
  children,
  style,
}: {
  children: React.ReactNode;
  style?: React.CSSProperties;
}) {
  return (
    <td
      style={{
        padding: "8px 10px",
        fontSize: 11.5,
        color: "#0f1f3d",
        ...style,
      }}
    >
      {children}
    </td>
  );
}

function toneColor(tone?: "good" | "bad" | "neutral"): string {
  if (tone === "good") return "#1f7a4d";
  if (tone === "bad") return "#b35a00";
  return "#0f1f3d";
}

// Hidden render slot — keeps the brief out of normal layout flow but visible
// to html2canvas. Use as a wrapper around <PolicyBrief ref={...} ... />.
export function HiddenBriefSlot({ children }: { children: React.ReactNode }) {
  return (
    <div
      aria-hidden
      style={{
        position: "fixed",
        left: -10000,
        top: 0,
        pointerEvents: "none",
        zIndex: -1,
      }}
    >
      {children}
    </div>
  );
}

